-- MySQL Script generated by MySQL Workbench
-- Sun Dec  9 10:48:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fat.protocolos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fat.protocolos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fat.protocolos` DEFAULT CHARACTER SET utf8 ;
USE `fat.protocolos` ;

-- -----------------------------------------------------
-- Table `fat.protocolos`.`motivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat.protocolos`.`motivo` ;

CREATE TABLE IF NOT EXISTS `fat.protocolos`.`motivo` (
  `pk_motivo` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(300) NULL,
  `excluido` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`pk_motivo`),
  UNIQUE INDEX `motivo_UNIQUE` (`motivo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat.protocolos`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat.protocolos`.`livro` ;

CREATE TABLE IF NOT EXISTS `fat.protocolos`.`livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `nome` VARCHAR(30) NULL,
  `detalhes` VARCHAR(300) NULL,
  `folhas` INT(4) NULL,
  `cor` VARCHAR(30) NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  `excluido` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat.protocolos`.`situacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat.protocolos`.`situacao` ;

CREATE TABLE IF NOT EXISTS `fat.protocolos`.`situacao` (
  `id_situacao` INT NOT NULL AUTO_INCREMENT,
  `situacao` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(300) NULL,
  `excluido` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_situacao`),
  UNIQUE INDEX `situacao_UNIQUE` (`situacao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat.protocolos`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat.protocolos`.`usuario` ;

CREATE TABLE IF NOT EXISTS `fat.protocolos`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `user` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `inserir` VARCHAR(1) NOT NULL,
  `editar` VARCHAR(1) NOT NULL,
  `excluir` VARCHAR(1) NOT NULL,
  `excluido` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat.protocolos`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat.protocolos`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `fat.protocolos`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `setor` VARCHAR(45) NULL,
  `descricao` VARCHAR(300) NULL,
  `excluido` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fat.protocolos`.`protocolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fat.protocolos`.`protocolo` ;

CREATE TABLE IF NOT EXISTS `fat.protocolos`.`protocolo` (
  `id_protocolo` INT NOT NULL AUTO_INCREMENT,
  `num_protocolo` INT(5) NOT NULL,
  `pagina` INT(4) NOT NULL,
  `fk_livro` INT NOT NULL,
  `fk_remetente` INT NOT NULL,
  `fk_destinatario` INT NOT NULL,
  `solicitante` VARCHAR(100) NULL,
  `data_lanc` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_receb` DATE NULL,
  `dt_previsao_dev` DATE NOT NULL,
  `data_devol` DATE NULL,
  `fk_situacao` INT NOT NULL,
  `fk_motivo` INT NOT NULL,
  `observacoes` VARCHAR(300) NULL,
  `fk_usuario` INT NOT NULL,
  `assinado` VARCHAR(1) NULL,
  PRIMARY KEY (`id_protocolo`),
  INDEX `fk_protocolo_motivo_idx` (`fk_motivo` ASC),
  INDEX `fk_protocolo_livro_idx` (`fk_livro` ASC),
  INDEX `fk_protocolo_situacao_idx` (`fk_situacao` ASC),
  INDEX `fk_protocolo_usuario_idx` (`fk_usuario` ASC),
  INDEX `fk_protocolo_remetente_idx` (`fk_remetente` ASC),
  INDEX `fk_protocolo_destinatario_idx` (`fk_destinatario` ASC),
  UNIQUE INDEX `num_protocolo_UNIQUE` (`num_protocolo` ASC),
  CONSTRAINT `fk_protocolo_motivo`
    FOREIGN KEY (`fk_motivo`)
    REFERENCES `fat.protocolos`.`motivo` (`pk_motivo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_protocolo_livro`
    FOREIGN KEY (`fk_livro`)
    REFERENCES `fat.protocolos`.`livro` (`id_livro`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_protocolo_situacao`
    FOREIGN KEY (`fk_situacao`)
    REFERENCES `fat.protocolos`.`situacao` (`id_situacao`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_protocolo_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `fat.protocolos`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_protocolo_remetente`
    FOREIGN KEY (`fk_remetente`)
    REFERENCES `fat.protocolos`.`pessoa` (`id_pessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_protocolo_destinatario`
    FOREIGN KEY (`fk_destinatario`)
    REFERENCES `fat.protocolos`.`pessoa` (`id_pessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
